"""added sale price to cart table.

Revision ID: c03582d43c7b
Revises: cb5efcde14ac
Create Date: 2024-09-27 12:04:02.862409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03582d43c7b'
down_revision = 'cb5efcde14ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_column('sale_price')

    # ### end Alembic commands ###
